env:
 global:
  - CC_TEST_REPORTER_ID=faecca074adf6422d1ee0fa828c479addfdef91d248a13c716c69702c0cdd88d

language: node_js

node_js:
 - stable

install:
 - npm install

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
 - npm test

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
 email: false